const DIGITS='0123456789';let LEN=3,last=null,view='quiz';const canvas=document.getElementById('canvas');const COLS=['#078cff','#33e633','#ff8a00','#a73cff','#ff2020','#078cff'];let quizTpl=localStorage.getItem('quizTpl')||null;let coverTpl=localStorage.getItem('coverTpl')||null;
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1600)}
function perms(chars,k){const out=[];function rec(p,r){if(p.length===k){out.push(p.join(''));return}for(let i=0;i<r.length;i++)rec([...p,r[i]],[...r.slice(0,i),...r.slice(i+1)])}rec([],chars.split(''));return out}
function ev(s,g){let b=0,c=0;for(let i=0;i<s.length;i++){if(s[i]===g[i])b++;else if(s.includes(g[i]))c++}return[b,c]}
function clueText(b,c){const m={'0,0':'NESSUNA CIFRA È PRESENTE','1,0':'UNA CIFRA È GIUSTA\nED È AL POSTO GIUSTO','0,1':'UNA CIFRA È GIUSTA\nMA NEL POSTO SBAGLIATO','2,0':'DUE CIFRE SONO GIUSTE\nED AL POSTO GIUSTO','0,2':'DUE CIFRE SONO GIUSTE\nMA NEL POSTO SBAGLIATO','1,1':'UNA CIFRA È AL POSTO GIUSTO\nE UNA NEL POSTO SBAGLIATO','3,0':'TRE CIFRE SONO GIUSTE\nED AL POSTO GIUSTO','0,3':'TRE CIFRE SONO GIUSTE\nMA NEL POSTO SBAGLIATO','2,1':'DUE CIFRE AL POSTO GIUSTO\nE UNA NEL POSTO SBAGLIATO','1,2':'UNA CIFRA AL POSTO GIUSTO\nE DUE NEL POSTO SBAGLIATO'};return m[b+','+c]||`${b} CIFRE AL POSTO GIUSTO\nE ${c} NEL POSTO SBAGLIATO`}
function sols(clues,cands){return cands.filter(code=>clues.every(cl=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c}))}
function prog(clues,cands){let a=[...cands],r=[];for(const cl of clues){a=a.filter(code=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c});r.push(a.length)}return r}
function useful(clues,cands){for(let i=0;i<clues.length;i++){if(sols(clues.slice(0,i).concat(clues.slice(i+1)),cands).length===1)return false}return true}
function connected(z,clues){const all=clues.slice(1).map(x=>x.g).join('');return [...z].every(d=>all.includes(d))}
function rand(a){return a[Math.floor(Math.random()*a.length)]}function sample(a,k){const b=[...a],o=[];for(let i=0;i<k;i++){const j=Math.floor(Math.random()*b.length);o.push(b.splice(j,1)[0])}return o}
function score(clues,cands){const p=clues.map(c=>c.b+','+c.c),pc=prog(clues,cands);let s=new Set(p).size*5+12;for(const x of p)if(['1,0','0,1','2,0','0,2','1,1','3,0','0,3','2,1','1,2'].includes(x))s+=3;if(pc[2]&&pc[2]<=2)s-=16;if(pc[3]===1)s-=8;return s}
function generate(){document.getElementById('status').textContent='Genero...';const count=LEN===5?6:5,cands=perms(DIGITS,LEN);let best=null,bs=-9999;for(let a=0;a<80000;a++){const secret=rand(cands),abs=[...DIGITS].filter(d=>!secret.includes(d));if(abs.length<LEN)continue;const zero=sample(abs,LEN).join(''),clues=[{g:zero,b:0,c:0}],used=new Set([zero,secret]);let tries=0;while(clues.length<count&&tries<1200){tries++;const g=rand(cands);if(used.has(g))continue;used.add(g);const [b,c]=ev(secret,g);if((b===0&&c===0)||(b===LEN&&c===0))continue;clues.push({g,b,c})}if(clues.length!==count)continue;if(!connected(zero,clues))continue;const so=sols(clues,cands);if(so.length!==1||so[0]!==secret)continue;if(!useful(clues,cands))continue;const sc=score(clues,cands);if(sc>bs){best={secret,clues,counts:prog(clues,cands)};bs=sc}if(sc>=31)break}if(!best){toast('Riprova: quiz non trovato');return}last=best;render();document.getElementById('status').textContent='Quiz verificato'}
function makeDesc(){return `Riesci a trovare il codice?\nCi sono ${last.clues.length} indizi e una sola soluzione corretta.\nScrivi la tua risposta nei commenti senza leggere gli altri!\nSolo il 2% riesce a risolverlo... e tu ce la farai?\n\n#quiz #rompicapo #indovinello #trovailcodice #perte`}
function makeText(){return last.clues.map(c=>`${c.g} → ${clueText(c.b,c.c).replaceAll('\n',' ')}`).join('\n')+`\n\nSoluzione: ${last.secret}`}
function makeReason(){let s='',c=perms(DIGITS,LEN);last.clues.forEach((cl,i)=>{c=c.filter(code=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c});s+=`${i+1}) ${cl.g}: ${clueText(cl.b,cl.c).replaceAll('\n',' ')}\n   Restano ${c.length} soluzioni\n\n`});return s+`Soluzione unica: ${last.secret}`}
function render(){if(!last)return;view==='cover'?renderCover():renderQuiz();renderSide()}
function renderSide(){document.getElementById('solBox').innerHTML=[...last.secret].map(d=>`<div>${d}</div>`).join('');document.getElementById('tries').textContent=last.clues.length;document.getElementById('lenStat').textContent=LEN;document.getElementById('time').textContent=new Date().toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});const start=perms(DIGITS,LEN).length;document.getElementById('progress').innerHTML=[`<div class="prog"><span>Inizio</span><b>${start}</b></div>`].concat(last.counts.map((c,i)=>`<div class="prog"><span>Dopo ${i+1}° indizio</span><b style="color:${c===1?'#3be65f':'#fff'}">${c}</b></div>`)).join('');document.getElementById('reason').textContent=makeReason();document.getElementById('desc').value=makeDesc()}
function renderQuiz(){const bg=quizTpl||'';document.getElementById('poster').innerHTML=`${bg?`<img src="${bg}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover">`:''}${previewOverlay()}`}
function renderCover(){const bg=coverTpl||'';document.getElementById('poster').innerHTML=`${bg?`<img src="${bg}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover">`:''}<div style="position:absolute;left:7%;right:7%;bottom:8%;background:#080808dd;border:2px solid #ffd21f;border-radius:12px;color:white;text-align:center;font-weight:1000;font-size:2.2vw;padding:2%">🔒 ${LEN} CIFRE | ${last.clues.length} INDIZI | 1 SOLA SOLUZIONE</div>`}
function layout(){const ys=LEN===5?[25.6,31.7,37.8,43.9,50.0,56.1]:[26.0,34.6,43.2,51.8,60.4];return ys.map(y=>({x:5.2,y,w:89.8,h:7.0,tile:LEN===3?4.85:LEN===4?3.75:3.05,tileH:LEN===3?5.55:LEN===4?4.75:4.05,font:LEN===3?3.5:LEN===4?2.85:2.25,text:LEN===5?1.85:2.25}))}
function previewOverlay(){const prev=document.getElementById('prev').value.trim();let html='';if(prev)html+=`<div style="position:absolute;left:32%;right:10%;top:22.3%;height:3.4%;display:grid;place-items:center;color:#111;font-weight:1000;font-size:1.9vw;text-shadow:none">SOLUZIONE PRECEDENTE: ${prev}</div>`;html+=last.clues.map((cl,i)=>{const r=layout()[i],col=COLS[i];return `<div style="position:absolute;left:${r.x}%;top:${r.y}%;width:${r.w}%;height:${r.h}%;background:#030303e8;border:1.5px solid ${col};border-radius:8px;box-shadow:0 0 14px ${col};display:flex;align-items:center;padding:0 1.6%;gap:1.3%"><div style="display:flex;gap:.7vw;min-width:${LEN===3?20:LEN===4?21:23}vw">${[...cl.g].map(d=>`<span style="display:grid;place-items:center;width:${r.tile}vw;height:${r.tileH}vw;background:#050505;border:2px solid ${col};border-radius:6px;box-shadow:0 0 10px ${col};font-size:${r.font}vw;font-weight:1000;color:white">${d}</span>`).join('')}</div><div style="font-size:3vw;color:${col};font-weight:1000">→</div><div style="flex:1;color:white;font-weight:1000;font-size:${r.text}vw;line-height:1.08;text-align:left">${clueText(cl.b,cl.c).replaceAll('\n','<br>')}</div></div>`}).join('');return html}
function loadImage(src){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=rej;img.src=src})}
function rr(ctx,x,y,w,h,r,fill,stroke,lw=2){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function text(ctx,s,x,y,size,color='white',align='left'){ctx.textAlign=align;ctx.font=`900 ${size}px Arial Black, Impact, Arial`;ctx.fillStyle=color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillText(s,x,y);ctx.shadowBlur=0}
function wrap(ctx,textValue,x,y,max,lineH){for(const part of textValue.split('\n')){let line='';for(const word of part.split(' ')){const t=line+word+' ';if(ctx.measureText(t).width>max&&line){ctx.fillText(line,x,y);y+=lineH;line=word+' '}else line=t}ctx.fillText(line,y?x:x,y);y+=lineH}return y}
function fallback(ctx){ctx.fillStyle='#020203';ctx.fillRect(0,0,1080,1920);const g=ctx.createRadialGradient(250,120,10,650,700,1150);g.addColorStop(0,'#333');g.addColorStop(.5,'#050505');g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920)}
async function base(kind){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,1080,1920);const src=kind==='quiz'?quizTpl:coverTpl;if(src){const img=await loadImage(src);ctx.drawImage(img,0,0,1080,1920)}else fallback(ctx);return ctx}
function layoutPx(){const ys=LEN===5?[492,609,726,843,960,1077]:[500,665,830,995,1160];return ys.map(y=>({x:70,y,w:940,h:130,tw:LEN===3?92:LEN===4?70:56,th:LEN===3?96:LEN===4?80:68,gap:LEN===3?16:LEN===4?10:7,fs:LEN===3?66:LEN===4?52:40,tx:LEN===3?520:LEN===4?505:500,text:LEN===5?31:40,line:LEN===5?34:44}))}
function drawTile(ctx,d,x,y,w,h,col,font){rr(ctx,x,y,w,h,12,'#050505',col,4);ctx.shadowColor=col;ctx.shadowBlur=18;ctx.stroke();ctx.shadowBlur=0;text(ctx,d,x+w/2,y+h*.72,font,'white','center')}
async function drawQuiz(){const ctx=await base('quiz');const prev=document.getElementById('prev').value.trim();if(prev){rr(ctx,330,410,640,48,6,'#ffd21f');text(ctx,`SOLUZIONE PRECEDENTE: ${prev}`,650,444,32,'#111','center')}layoutPx().forEach((r,i)=>{const col=COLS[i],cl=last.clues[i];rr(ctx,45,r.y-14,990,r.h+28,15,'#030303ee',col,3);let x=r.x;[...cl.g].forEach(d=>{drawTile(ctx,d,x,r.y+(r.h-r.th)/2,r.tw,r.th,col,r.fs);x+=r.tw+r.gap});text(ctx,'→',x+36,r.y+r.h*.62,56,col,'center');ctx.font=`900 ${r.text}px Arial Black, Impact, Arial`;ctx.fillStyle='white';ctx.textAlign='left';ctx.shadowColor='#000';ctx.shadowBlur=8;wrap(ctx,clueText(cl.b,cl.c),r.tx,r.y+48,1010-r.tx,r.line);ctx.shadowBlur=0});return canvas}
async function drawCover(){const ctx=await base('cover');rr(ctx,70,1600,940,96,14,'#050505dd','#ffd21f',5);text(ctx,`🔒 ${LEN} CIFRE | ${last.clues.length} INDIZI | 1 SOLA SOLUZIONE`,540,1662,43,'white','center');return canvas}
function download(c,name){const a=document.createElement('a');a.download=name;a.href=c.toDataURL('image/png');a.click()}
function setupUpload(id,key,cb){document.getElementById(id).addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{localStorage.setItem(key,r.result);cb(r.result);render();toast('Template salvato')};r.readAsDataURL(f)})}
setupUpload('tplQuiz','quizTpl',v=>quizTpl=v);setupUpload('tplCover','coverTpl',v=>coverTpl=v);document.getElementById('clearTpl').onclick=()=>{localStorage.removeItem('quizTpl');localStorage.removeItem('coverTpl');quizTpl=null;coverTpl=null;render();toast('Template rimossi')};
document.querySelectorAll('.choice').forEach(x=>x.onclick=()=>{document.querySelectorAll('.choice').forEach(y=>y.classList.remove('active'));x.classList.add('active');LEN=+x.dataset.len;generate()});document.getElementById('prev').oninput=render;document.getElementById('gen').onclick=generate;document.getElementById('reset').onclick=()=>{document.getElementById('prev').value='';generate()};function copy(txt,msg){navigator.clipboard.writeText(txt);toast(msg)}document.getElementById('copyQuiz').onclick=()=>copy(makeText(),'Quiz copiato');document.getElementById('copyDesc').onclick=()=>copy(document.getElementById('desc').value,'Descrizione copiata');document.getElementById('tabQuiz').onclick=()=>{view='quiz';tabQuiz.classList.add('active');tabCover.classList.remove('active');render()};document.getElementById('tabCover').onclick=()=>{view='cover';tabCover.classList.add('active');tabQuiz.classList.remove('active');render()};document.getElementById('exportQuiz').onclick=async()=>{download(await drawQuiz(),`quiz_${last.secret}.png`);toast('Quiz esportato')};document.getElementById('exportCover').onclick=async()=>{download(await drawCover(),`copertina_${last.secret}.png`);toast('Copertina esportata')};generate();
