const DIGITS='0123456789';
let LEN=3,last=null;
const canvas=document.getElementById('canvas');
const overlayCanvas=document.getElementById('overlayCanvas');
const COLORS=['#079cff','#20f14a','#ff9d00','#b93cff','#ff3030','#ffffff','#ffd21f'];
const CACHE={};

function toast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1400)}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function rnd(a){return a[Math.floor(Math.random()*a.length)]}
function candidates(n){if(CACHE[n])return CACHE[n];const out=[];function rec(p,r){if(p.length===n){out.push(p);return}for(let i=0;i<r.length;i++)rec(p+r[i],r.slice(0,i)+r.slice(i+1))}rec('',DIGITS);CACHE[n]=out;return out}
function ev(s,g){let b=0,c=0;for(let i=0;i<s.length;i++){if(s[i]===g[i])b++;else if(s.includes(g[i]))c++}return[b,c]}
function clueText(b,c){const m={'0,0':'NESSUNA CIFRA È\nPRESENTE','1,0':'UNA CIFRA È GIUSTA\nED È AL POSTO GIUSTO','0,1':'UNA CIFRA È GIUSTA\nMA NEL POSTO SBAGLIATO','2,0':'DUE CIFRE SONO GIUSTE\nED AL POSTO GIUSTO','0,2':'DUE CIFRE SONO GIUSTE\nMA NEL POSTO SBAGLIATO','1,1':'UNA CIFRA È AL POSTO GIUSTO\nE UNA NEL POSTO SBAGLIATO','2,1':'DUE CIFRE AL POSTO GIUSTO\nE UNA NEL POSTO SBAGLIATO','1,2':'UNA CIFRA AL POSTO GIUSTO\nE DUE NEL POSTO SBAGLIATO'};return m[b+','+c]||`${b} CIFRE AL POSTO GIUSTO\nE ${c} NEL POSTO SBAGLIATO`}
function sols(clues,cands){return cands.filter(code=>clues.every(cl=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c}))}
function progress(clues,cands){let a=[...cands],r=[];for(const cl of clues){a=a.filter(code=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c});r.push(a.length)}return r}
function pattern(){return LEN===3?[[0,0],[0,1],[1,0],[0,2],[1,1]]:LEN===4?[[0,0],[0,1],[1,0],[0,2],[1,1]]:[[0,0],[0,1],[1,0],[0,2],[1,1],[1,2]]}
function quality(clues,counts){const keys=clues.map(x=>x.b+','+x.c);let score=0;score+=new Set(keys).size*8;score-=keys.filter(k=>k==='1,0').length*7;score+=keys.filter(k=>k==='0,2'||k==='1,1'||k==='1,2').length*10;if(counts[1]&&counts[1]<4)score-=50;if(counts[2]&&counts[2]<2)score-=30;if(counts.at(-2)===1)score-=25;if(counts.at(-1)===1)score+=40;for(let i=1;i<counts.length;i++)if(counts[i]<counts[i-1])score+=3;return score}
function buildFallback(secret){const abs=shuffle(DIGITS.split('').filter(d=>!secret.includes(d)));const clues=[];clues.push({g:abs.slice(0,LEN).join(''),b:0,c:0});for(let i=0;i<LEN;i++){const g=abs.slice(0,LEN);g[i]=secret[i];const e=ev(secret,g.join(''));clues.push({g:g.join(''),b:e[0],c:e[1]})}return clues.slice(0,LEN===5?6:5)}
function generateCandidate(cands){const secret=rnd(cands);const pat=pattern();const shuffled=shuffle(cands.filter(x=>x!==secret));const clues=[];const used=new Set();for(const p of pat){const pool=[];for(const g of shuffled){if(used.has(g))continue;const e=ev(secret,g);if(e[0]===p[0]&&e[1]===p[1])pool.push(g);if(pool.length>70)break}if(!pool.length)return null;const g=rnd(pool);used.add(g);clues.push({g,b:p[0],c:p[1]})}const so=sols(clues,cands);if(so.length!==1||so[0]!==secret)return null;const counts=progress(clues,cands);return{secret,clues,counts,score:quality(clues,counts)}}
function generate(){document.getElementById('status').textContent='Genero...';setTimeout(()=>{const c=candidates(LEN);let best=null;const max=LEN===5?90:180;for(let i=0;i<max;i++){const q=generateCandidate(c);if(q&&(!best||q.score>best.score))best=q;if(best&&best.score>60)break}if(!best){const secret=rnd(c);const clues=buildFallback(secret);best={secret,clues,counts:progress(clues,c),score:0}}last=best;render();document.getElementById('status').textContent='Quiz verificato'},10)}
function makeDesc(){return `Riesci a trovare il codice?\nCi sono ${last.clues.length} indizi e una sola soluzione corretta.\nScrivi solo le ${LEN} cifre nei commenti senza leggere gli altri!\n\n#quiz #rompicapo #indovinello #trovailcodice #perte`}
function makeText(){return last.clues.map(c=>`${c.g} → ${clueText(c.b,c.c).replaceAll('\n',' ')}`).join('\n')+`\n\nSoluzione: ${last.secret}`}
function makeReason(){let s='',c=candidates(LEN);last.clues.forEach((cl,i)=>{c=c.filter(code=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c});s+=`${i+1}) ${cl.g}: ${clueText(cl.b,cl.c).replaceAll('\n',' ')}\n   Restano ${c.length} soluzioni\n\n`});return s+`Soluzione unica: ${last.secret}`}
function render(){if(!last)return;drawQuiz(true);document.getElementById('solBox').innerHTML=[...last.secret].map(d=>`<div>${d}</div>`).join('');document.getElementById('prevMirror').value=document.getElementById('prev').value.trim()||'-';document.getElementById('lenMirror').value=LEN;document.getElementById('codeMirror').value=last.secret;document.getElementById('desc').value=makeDesc();document.getElementById('reason').textContent=makeReason();document.getElementById('progress').innerHTML=[`<div class="prog"><span>Inizio</span><b>${candidates(LEN).length}</b></div>`].concat(last.counts.map((n,i)=>`<div class="prog"><span>Dopo ${i+1}° indizio</span><b style="color:${n===1?'#3be65f':'#fff'}">${n}</b></div>`)).join('')}

function rr(ctx,x,y,w,h,r,fill,stroke,lw=2){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function text(ctx,s,x,y,size,color='white',align='left',font='Impact, Arial Black, Arial'){ctx.textAlign=align;ctx.font=`900 ${size}px ${font}`;ctx.fillStyle=color;ctx.shadowColor='#000';ctx.shadowBlur=10;ctx.fillText(s,x,y);ctx.shadowBlur=0}
function bg(ctx){ctx.fillStyle='#020202';ctx.fillRect(0,0,1080,1920);const g=ctx.createRadialGradient(540,500,20,540,800,1200);g.addColorStop(0,'#191919');g.addColorStop(.42,'#070707');g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920);ctx.globalAlpha=.14;for(let y=0;y<1920;y+=40){ctx.fillStyle='#fff';ctx.fillRect(0,y,1080,1)}ctx.globalAlpha=1;for(let i=0;i<80;i++){ctx.fillStyle=i%2?'#ff9d00':'#079cff';ctx.globalAlpha=.24;ctx.beginPath();ctx.arc((i*197)%1080,(i*83)%1780,1+(i%3),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function lock(ctx,x,y,s){ctx.save();ctx.translate(x,y);ctx.shadowColor='#ffd21f';ctx.shadowBlur=28;ctx.strokeStyle='#ffd21f';ctx.lineWidth=s*.065;ctx.beginPath();ctx.arc(0,-s*.15,s*.29,Math.PI,0);ctx.stroke();let g=ctx.createLinearGradient(-s*.35,-s*.1,s*.35,s*.45);g.addColorStop(0,'#6a6a6a');g.addColorStop(.48,'#151515');g.addColorStop(1,'#050505');rr(ctx,-s*.36,-s*.08,s*.72,s*.58,s*.08,g,'#ffd21f',s*.035);ctx.shadowBlur=0;ctx.fillStyle='#ffd21f';ctx.beginPath();ctx.arc(0,s*.13,s*.07,0,Math.PI*2);ctx.fill();ctx.fillRect(-s*.025,s*.13,s*.05,s*.16);ctx.restore()}
function template(ctx){bg(ctx);text(ctx,'TROVA IL',62,155,132,'#f7f7f7');text(ctx,'CODICE',48,365,190,'#ffd21f');lock(ctx,900,205,205);ctx.shadowColor='#ffd21f';ctx.shadowBlur=20;rr(ctx,125,410,830,82,7,'#ffd21f');ctx.shadowBlur=0;text(ctx,'SOLUZIONE PRECEDENTE:',165,468,45,'#121212');rr(ctx,740,422,195,58,5,'#050505','#ffd21f',3);const prev=document.getElementById('prev').value.trim()||'---';text(ctx,prev,838,467,49,'white','center')}
function spec(){if(LEN===5)return{ys:[535,690,845,1000,1155,1310],h:125,bw:52,bh:72,gap:8,x:58,arr:405,tx:470,tf:31,line:37,bottom:1480};if(LEN===4)return{ys:[535,700,865,1030,1195],h:136,bw:68,bh:84,gap:11,x:58,arr:415,tx:480,tf:35,line:42,bottom:1415};return{ys:[535,700,865,1030,1195],h:136,bw:82,bh:92,gap:15,x:68,arr:420,tx:480,tf:35,line:42,bottom:1415}}
function drawEmptyRows(ctx,r){for(let i=0;i<r.ys.length;i++){const col=COLORS[i],y=r.ys[i];ctx.save();ctx.shadowColor=col;ctx.shadowBlur=18;rr(ctx,42,y,996,r.h,16,'#050505e8',col,3);ctx.restore();let x=r.x;for(let j=0;j<LEN;j++){ctx.save();ctx.shadowColor=col;ctx.shadowBlur=13;rr(ctx,x,y+(r.h-r.bh)/2,r.bw,r.bh,10,'#050505',col,3);ctx.restore();x+=r.bw+r.gap}text(ctx,'➜',r.arr,y+r.h*.67,53,col,'center','Arial Black,Arial');rr(ctx,r.tx-18,y+16,1030-r.tx,r.h-32,9,'#020202',col,2)}}
function drawBottom(ctx,r){ctx.save();ctx.shadowColor='#ffd21f';ctx.shadowBlur=18;rr(ctx,44,r.bottom,992,360,18,'#050505ee','#ffd21f',3);ctx.restore();text(ctx,'QUAL È IL',82,r.bottom+120,86,'white');text(ctx,'CODICE?',82,r.bottom+218,102,'#ffd21f');let bw=LEN===3?122:LEN===4?100:82,bh=LEN===3?115:LEN===4?100:88,gap=LEN===3?28:20,total=LEN*bw+(LEN-1)*gap,bx=690-total/2;for(let i=0;i<LEN;i++){ctx.save();ctx.shadowColor='#ffd21f';ctx.shadowBlur=22;rr(ctx,bx+i*(bw+gap),r.bottom+80,bw,bh,14,'#050505','#ffd21f',5);ctx.restore()}text(ctx,'SCRIVI SOLO',735,r.bottom+255,40,'white','center');text(ctx,`${LEN} CIFRE`,735,r.bottom+310,55,'#ffd21f','center')}
function drawTile(ctx,d,x,y,w,h,col){ctx.save();ctx.shadowColor=col;ctx.shadowBlur=16;rr(ctx,x,y,w,h,10,'#050505',col,4);ctx.restore();text(ctx,d,x+w/2,y+h*.72,Math.floor(h*.66),'white','center')}
function drawClue(ctx,cl,x,y,size,line,col){const parts=clueText(cl.b,cl.c).split('\n');ctx.font=`900 ${size}px Arial Black, Impact, Arial`;ctx.textAlign='left';ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillStyle='white';ctx.fillText(parts[0],x,y);if(parts[1]){const accents=['PRESENTE','POSTO SBAGLIATO','POSTO GIUSTO'];let done=false;for(const phrase of accents){const idx=parts[1].indexOf(phrase);if(idx>=0){const before=parts[1].slice(0,idx);ctx.fillStyle='white';ctx.fillText(before,x,y+line);ctx.fillStyle=col;ctx.fillText(phrase,x+ctx.measureText(before).width+5,y+line);done=true;break}}if(!done){ctx.fillStyle=col;ctx.fillText(parts[1],x,y+line)}}ctx.shadowBlur=0}
function fillRows(ctx,r){last.clues.forEach((cl,i)=>{const col=COLORS[i],y=r.ys[i];let x=r.x;[...cl.g].forEach(d=>{drawTile(ctx,d,x,y+(r.h-r.bh)/2,r.bw,r.bh,col);x+=r.bw+r.gap});drawClue(ctx,cl,r.tx,y+r.h*.43,r.tf,r.line,col)})}
function drawQuiz(preview=false){canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,1080,1920);template(ctx);const r=spec();drawEmptyRows(ctx,r);drawBottom(ctx,r);fillRows(ctx,r);if(preview)document.getElementById('poster').innerHTML=`<img src="${canvas.toDataURL('image/jpeg',.9)}" style="width:100%;height:100%;object-fit:cover">`;return canvas}

function overlaySpec(){if(LEN===5)return{h:116,bw:52,bh:70,gap:8,x:34,arr:382,tx:445,tf:29,line:34,rows:6,gapY:12};if(LEN===4)return{h:128,bw:68,bh:82,gap:11,x:40,arr:395,tx:458,tf:34,line:40,rows:5,gapY:14};return{h:130,bw:82,bh:90,gap:15,x:44,arr:402,tx:465,tf:35,line:41,rows:5,gapY:14}}
function drawCluesOverlay(){const o=overlaySpec();const totalH=o.rows*o.h+(o.rows-1)*o.gapY+32;overlayCanvas.width=1080;overlayCanvas.height=totalH;const ctx=overlayCanvas.getContext('2d');ctx.clearRect(0,0,overlayCanvas.width,overlayCanvas.height);last.clues.forEach((cl,i)=>{const col=COLORS[i],y=16+i*(o.h+o.gapY);ctx.save();ctx.shadowColor=col;ctx.shadowBlur=18;rr(ctx,22,y,1036,o.h,16,'rgba(3,3,3,.94)',col,3);ctx.restore();let x=o.x;[...cl.g].forEach(d=>{drawTile(ctx,d,x,y+(o.h-o.bh)/2,o.bw,o.bh,col);x+=o.bw+o.gap});text(ctx,'➜',o.arr,y+o.h*.67,52,col,'center','Arial Black,Arial');rr(ctx,o.tx-18,y+15,1050-o.tx,o.h-30,9,'rgba(2,2,2,.95)',col,2);drawClue(ctx,cl,o.tx,y+o.h*.43,o.tf,o.line,col)});return overlayCanvas}
function download(c,name){const a=document.createElement('a');a.download=name;a.href=c.toDataURL('image/png');a.click()}

document.querySelectorAll('.choice').forEach(x=>x.onclick=()=>{document.querySelectorAll('.choice').forEach(y=>y.classList.remove('active'));x.classList.add('active');LEN=+x.dataset.len;generate()});
document.getElementById('prev').oninput=render;
document.getElementById('gen').onclick=generate;
document.getElementById('regen').onclick=generate;
document.getElementById('reset').onclick=()=>{document.getElementById('prev').value='';generate()};
function copy(txt,msg){navigator.clipboard.writeText(txt);toast(msg)}
document.getElementById('copyQuiz').onclick=()=>copy(makeText(),'Quiz copiato');
document.getElementById('copyDesc').onclick=()=>copy(document.getElementById('desc').value,'Descrizione copiata');
document.getElementById('exportQuiz').onclick=()=>{download(drawQuiz(false),`quiz_${last.secret}.png`);toast('Immagine completa esportata')};
document.getElementById('exportClues').onclick=()=>{download(drawCluesOverlay(),`indizi_${last.secret}.png`);toast('PNG degli indizi esportato')};
generate();