const DIGITS='0123456789';let LEN=3,last=null;const canvas=document.getElementById('canvas');let tpl=localStorage.getItem('quizTemplate')||null;
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1400)}
function rand(a){return a[Math.floor(Math.random()*a.length)]}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function perms(chars,k){const out=[];function rec(p,r){if(p.length===k){out.push(p.join(''));return}for(let i=0;i<r.length;i++)rec([...p,r[i]],[...r.slice(0,i),...r.slice(i+1)])}rec([],chars.split(''));return out}
function ev(s,g){let b=0,c=0;for(let i=0;i<s.length;i++){if(s[i]===g[i])b++;else if(s.includes(g[i]))c++}return[b,c]}
function clueText(b,c){const m={'0,0':'NESSUNA CIFRA È\nPRESENTE','1,0':'UNA CIFRA È GIUSTA\nED È AL POSTO GIUSTO','0,1':'UNA CIFRA È GIUSTA\nMA NEL POSTO SBAGLIATO','2,0':'DUE CIFRE SONO GIUSTE\nED AL POSTO GIUSTO','0,2':'DUE CIFRE SONO GIUSTE\nMA NEL POSTO SBAGLIATO','1,1':'UNA CIFRA È AL POSTO GIUSTO\nE UNA NEL POSTO SBAGLIATO'};return m[b+','+c]||`${b} CIFRE AL POSTO GIUSTO\nE ${c} NEL POSTO SBAGLIATO`}
function sols(clues,cands){return cands.filter(code=>clues.every(cl=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c}))}
function prog(clues,cands){let a=[...cands],r=[];for(const cl of clues){a=a.filter(code=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c});r.push(a.length)}return r}
function absentGuess(abs){return shuffle(abs).slice(0,LEN).join('')}
function oneRight(secret,abs,pos){const g=shuffle(abs).slice(0,LEN);g[pos]=secret[pos];return g.join('')}
function oneWrong(secret,abs,pos){const g=shuffle(abs).slice(0,LEN);const to=(pos+1)%LEN;g[to]=secret[pos];return g.join('')}
function generate(){document.getElementById('status').textContent='Genero...';setTimeout(()=>{const secret=shuffle(DIGITS.split('')).slice(0,LEN).join('');const abs=DIGITS.split('').filter(d=>!secret.includes(d));const clues=[];const used=new Set();function add(g){if(!used.has(g)){used.add(g);const [b,c]=ev(secret,g);clues.push({g,b,c})}}add(absentGuess(abs));for(let i=0;i<LEN;i++)add(oneRight(secret,abs,i));while(clues.length<(LEN===5?6:5)){add(oneWrong(secret,abs,clues.length%LEN))}const cands=perms(DIGITS,LEN);const so=sols(clues,cands);if(so.length!==1||so[0]!==secret){generate();return}last={secret,clues,counts:prog(clues,cands)};render();document.getElementById('status').textContent='Quiz verificato'},20)}
function makeDesc(){return `Riesci a trovare il codice?\nCi sono ${last.clues.length} indizi e una sola soluzione corretta.\nScrivi solo le ${LEN} cifre nei commenti senza leggere gli altri!\n\n#quiz #rompicapo #indovinello #trovailcodice #perte`}
function makeText(){return last.clues.map(c=>`${c.g} → ${clueText(c.b,c.c).replaceAll('\n',' ')}`).join('\n')+`\n\nSoluzione: ${last.secret}`}
function makeReason(){let s='',c=perms(DIGITS,LEN);last.clues.forEach((cl,i)=>{c=c.filter(code=>{const e=ev(code,cl.g);return e[0]===cl.b&&e[1]===cl.c});s+=`${i+1}) ${cl.g}: ${clueText(cl.b,cl.c).replaceAll('\n',' ')}\n   Restano ${c.length} soluzioni\n\n`});return s+`Soluzione unica: ${last.secret}`}
function render(){if(!last)return;drawQuiz(true);renderSide()}
function renderSide(){document.getElementById('solBox').innerHTML=[...last.secret].map(d=>`<div>${d}</div>`).join('');document.getElementById('tries').textContent=last.clues.length;document.getElementById('lenStat').textContent=LEN;document.getElementById('time').textContent=new Date().toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});const start=perms(DIGITS,LEN).length;document.getElementById('progress').innerHTML=[`<div class="prog"><span>Inizio</span><b>${start}</b></div>`].concat(last.counts.map((c,i)=>`<div class="prog"><span>Dopo ${i+1}° indizio</span><b style="color:${c===1?'#3be65f':'#fff'}">${c}</b></div>`)).join('');document.getElementById('reason').textContent=makeReason();document.getElementById('desc').value=makeDesc()}
function loadImg(src){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=rej;img.src=src})}
function rr(ctx,x,y,w,h,r,fill,stroke,lw=2){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function text(ctx,s,x,y,size,color='white',align='left'){ctx.textAlign=align;ctx.font=`900 ${size}px Arial Black, Impact, Arial`;ctx.fillStyle=color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillText(s,x,y);ctx.shadowBlur=0}
function lines(ctx,t,x,y,lineH){t.split('\n').forEach(line=>{ctx.fillText(line,x,y);y+=lineH})}
function builtInTemplate(ctx){ctx.fillStyle='#020203';ctx.fillRect(0,0,1080,1920);const g=ctx.createRadialGradient(220,120,20,650,720,1250);g.addColorStop(0,'#303030');g.addColorStop(.42,'#060606');g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920);ctx.globalAlpha=.12;for(let y=0;y<1920;y+=42){ctx.fillStyle='#fff';ctx.fillRect(0,y,1080,1)}ctx.globalAlpha=1;safe(ctx,35,48,250,300);lock(ctx,905,145,145);text(ctx,'TROVA IL',320,130,88);text(ctx,'CODICE',320,265,132,'#ffd21f');rr(ctx,302,365,720,55,6,'#ffd21f');rr(ctx,34,1365,1012,390,16,'#050505e8','#555',3);text(ctx,'QUAL È IL',110,1505,88);text(ctx,'CODICE?',600,1505,88,'#ffd21f');ctx.fillStyle='#c78b00';for(let x=0;x<1080;x+=68){ctx.save();ctx.translate(x,1835);ctx.rotate(-.3);ctx.fillRect(0,0,45,22);ctx.restore()}}
function safe(ctx,x,y,w,h){let g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,'#777');g.addColorStop(.4,'#15171a');g.addColorStop(1,'#030303');ctx.shadowColor='#ff9a00';ctx.shadowBlur=24;rr(ctx,x,y,w,h,22,g,'#999',6);ctx.shadowBlur=0;ctx.strokeStyle='#111';ctx.lineWidth=8;ctx.strokeRect(x+28,y+28,w-56,h-56);ctx.beginPath();ctx.arc(x+w*.5,y+h*.36,w*.18,0,Math.PI*2);ctx.strokeStyle='#ddd';ctx.lineWidth=10;ctx.stroke();ctx.save();ctx.translate(x+w*.5,y+h*.68);ctx.rotate(Math.PI/4);rr(ctx,-9,-48,18,102,9,'#ddd');ctx.restore()}
function lock(ctx,x,y,s){ctx.save();ctx.translate(x,y);ctx.shadowColor='#ffb000';ctx.shadowBlur=22;ctx.strokeStyle='#ffd21f';ctx.lineWidth=s*.08;ctx.beginPath();ctx.arc(0,-s*.18,s*.32,Math.PI,0);ctx.stroke();let g=ctx.createLinearGradient(-s*.35,-s*.15,s*.35,s*.45);g.addColorStop(0,'#555');g.addColorStop(.55,'#111');g.addColorStop(1,'#000');rr(ctx,-s*.38,-s*.1,s*.76,s*.62,s*.08,g,'#ffd21f',s*.035);ctx.restore()}
function rowSpec(){if(LEN===5)return{ys:[455,570,685,800,915,1030],boxW:56,boxH:70,gap:7,numFont:40,txtX:505,txtFont:31,line:36};if(LEN===4)return{ys:[455,620,785,950,1115],boxW:72,boxH:84,gap:10,numFont:52,txtX:520,txtFont:36,line:42};return{ys:[455,620,785,950,1115],boxW:94,boxH:104,gap:16,numFont:68,txtX:520,txtFont:41,line:48}}
function drawTile(ctx,d,x,y,w,h,col,f){rr(ctx,x,y,w,h,12,'#050505',col,4);ctx.shadowColor=col;ctx.shadowBlur=16;ctx.stroke();ctx.shadowBlur=0;text(ctx,d,x+w/2,y+h*.72,f,'white','center')}
async function drawQuiz(preview=false){canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,1080,1920);if(tpl){const img=await loadImg(tpl);ctx.drawImage(img,0,0,1080,1920)}else builtInTemplate(ctx);const prev=document.getElementById('prev').value.trim();if(prev)text(ctx,`SOLUZIONE PRECEDENTE: ${prev}`,662,403,35,'#111','center');const r=rowSpec(),cols=['#078cff','#33e633','#ff9200','#a83cff','#ff2020','#078cff'];last.clues.forEach((cl,i)=>{const col=cols[i],y=r.ys[i];ctx.shadowColor=col;ctx.shadowBlur=13;rr(ctx,38,y,1004,138,14,'#030303e8',col,3);ctx.shadowBlur=0;let x=72;[...cl.g].forEach(d=>{drawTile(ctx,d,x,y+18,r.boxW,r.boxH,col,r.numFont);x+=r.boxW+r.gap});text(ctx,'→',438,y+90,58,col,'center');ctx.font=`900 ${r.txtFont}px Arial Black, Impact, Arial`;ctx.fillStyle='white';ctx.textAlign='left';ctx.shadowColor='#000';ctx.shadowBlur=8;lines(ctx,clueText(cl.b,cl.c),r.txtX,y+55,r.line);ctx.shadowBlur=0});let bw=LEN===3?132:LEN===4?110:90,bh=LEN===3?128:LEN===4?112:95,gap=LEN===3?36:24,total=LEN*bw+(LEN-1)*gap,bx=540-total/2;for(let i=0;i<LEN;i++){ctx.shadowColor='#ffd21f';ctx.shadowBlur=20;rr(ctx,bx+i*(bw+gap),1570,bw,bh,18,'#070707','#ffd21f',6);ctx.shadowBlur=0}text(ctx,`SCRIVI SOLO ${LEN} CIFRE`,540,1740,54,'white','center');if(preview){document.getElementById('poster').innerHTML=`<img src="${canvas.toDataURL('image/jpeg',.82)}" style="width:100%;height:100%;object-fit:cover">`}return canvas}
function download(c,name){const a=document.createElement('a');a.download=name;a.href=c.toDataURL('image/png');a.click()}
document.getElementById('tplQuiz').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{tpl=r.result;localStorage.setItem('quizTemplate',tpl);render();toast('Template salvato')};r.readAsDataURL(f)});document.getElementById('clearTpl').onclick=()=>{localStorage.removeItem('quizTemplate');tpl=null;render();toast('Template rimosso')};
document.querySelectorAll('.choice').forEach(x=>x.onclick=()=>{document.querySelectorAll('.choice').forEach(y=>y.classList.remove('active'));x.classList.add('active');LEN=+x.dataset.len;generate()});document.getElementById('prev').oninput=render;document.getElementById('gen').onclick=generate;document.getElementById('reset').onclick=()=>{document.getElementById('prev').value='';generate()};function copy(txt,msg){navigator.clipboard.writeText(txt);toast(msg)}document.getElementById('copyQuiz').onclick=()=>copy(makeText(),'Quiz copiato');document.getElementById('copyDesc').onclick=()=>copy(document.getElementById('desc').value,'Descrizione copiata');document.getElementById('exportQuiz').onclick=async()=>{download(await drawQuiz(false),`quiz_${last.secret}.png`);toast('Immagine esportata')};generate();
